//Variables:
//variable is a location used to store data.
//which is esally exacible in future use.
//--var
var x=23
//let
let x=45
let t=60
//rules or variable
//rules or variable
//1.varaible can not start with any number
//1.varaible can not start with any number
//let 56=90//erroe
//let 56=90//erroe
//2.variable can not start with any symbol,exclude(_)
//2.variable can not start with any symbol,exclude(_)
//let _34=88;
//let _34=88;
//let LAST_NAME="KAR";
//let LAST_NAME="KAR";
//3.variable can not include whitespace
//4.VARIABLES IN javascript are case - senstive
// let a=34;
//let A=34;
let x=33;
let y=23;
res=x+y
console.log("result:",res)
//data type in javascript.
//1.primitive data type
//* numbers (float,positive,negative)
//* strings
//* undifined
//* null
//* Boolean



